export enum ENUM_RESPONSE_STATUS {
  CONNECTION_ESTABLISHED_STATUS = 2002,
  CONNECTION_UNKNOWN_STATUS = 7001,
  OPERATION_UNVALID_STATUS = 7002,
  OPERATION_EMPTY_DATA_STATUS = 3000,
  OPERATION_SUCCESS_STATUS = 2000,
}
